fix: pass denom to inside funcs
hyphacoop/cosmos-genesis-tinkerer pull request #21
Opened 2022-06-06 21:15 UTC by RafilxTenfen

- Basically sends the denom to `increase_balance` to increase the amount of the same denom as sent to `increase_delegator_stake_to_validator`

2022-06-08 01:01 UTC, dasanchez requested changes
Hi @RafilxTenfen 
Thank you for submitting this fix! I requested a change just so the pylint check doesn't fail.
Could you share what your use case is for this repo? We're curious about how this tool is being used 😄

2022-06-08 01:01 UTC, dasanchez commented on cosmos_genesis_tinker.py
> +            operator_address=validator.operator_address, increase=increase['amount'], denom=increase['denom'])
pylint fails here because the line is too long, could you break it up please?

2022-06-16 13:52 UTC, RafilxTenfen commented
> Hi @RafilxTenfen Thank you for submitting this fix! I requested a change just so the pylint check doesn't fail. Could you share what your use case is for this repo? We're curious about how this tool is being used smile

For sure, So, right now we used to be able to do a fork of umeemania (umee testnet) locally to run an upgrade and see if it is going to break something :sweat_smile: 

So we basically swap one validator, increase the stake amount to 3 * total supply for the node to be able to produce blocks by himself and then we test the upgrade handler ^^

2022-06-22 19:32 UTC, dasanchez approved these changes
Thanks @RafilxTenfen !

2022-06-22 19:42 UTC, dasanchez commented
@RafilxTenfen Thanks for the info and for making the change!

It sounds like you are using this tool for the exact same purpose we are. Here are some more details on how the genesis tinkerer fits in with the rest of our tooling:

- We have a [GitHub Actions workflow](https://github.com/hyphacoop/cosmos-ansible/actions/runs/2543777730) that sets up a node in a fresh state, runs a software upgrade proposal, and checks that nodes are still being produced post-upgrade.
- A [separate workflow](https://github.com/hyphacoop/cosmos-ansible/actions/runs/2521731511) that runs twice a month produces tinkered genesis files based on mainnet exports.
- We are now working on a workflow that will test the upgrade process on a stateful local testnet on a regular basis (as soon as a new tinkered genesis file is generated).

Maybe there's an opportunity for some more collaboration! We'd be happy to work together to make the [cosmos-ansible](https://github.com/hyphacoop/cosmos-ansible) repo compatible with umee 😃

2022-06-22 19:43 UTC, merged

2022-06-22 21:47 UTC, RafilxTenfen commented
https://github.com/hyphacoop/cosmos-genesis-tinkerer/pull/21#issuecomment-1163531342

@dreamcodez @khoerling